#!/usr/bin/env zsh
# Provide Markdown document as an argument.

mkdir -p output

doc="${1:t:r}"
cat "$1" \
  | pandoc -t latex --pdf-engine=xelatex \
    --metadata geometry:margin=1in \
    --output=output/$doc.pdf
